customhost = "database-2.ctqnwsyshmgh.us-east-1.rds.amazonaws.com"
customuser = "devayan"
custompass = "(6h8dnBv^VNJKdx"
customdb = "userinfo"
custombucket = "aws-project-jobsearch-s3-bucket"
customregion = "us-east-1"
