customhost = "database-1.ctqnwsyshmgh.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "(6h8dnBv^VNJKdx"
customdb = "project"
custombucket = "site-project-bucket"
customregion = "us-east-1"
